### ISSUE TITLE
Netgsm Çalışmıyor

### ISSUE THREAD

**Issue by Gokhanu** [AktuelSistem/WHMCS-SmsModule#49]
Merhaba, modülü büyük hevesle indirdim kurdum, NETGSM abonesiyim api izni aldım fakat modül gönderim yapmıyor.

**Comment by necocan** [comment]
merhaba bende netgsm abonesiyim altta 50 adet sms kaldı diyor ancak sms ler gitmiyor tek sms gönder dediğindede hata diyip göndermiyor
