### ISSUE TITLE
Request : Ability to select SMS Provider

### ISSUE THREAD

**Issue by yashodhank** [AktuelSistem/WHMCS-SmsModule#76]
As by default one can select single SMS provider at present.
Can we add functionality use multiple SMS Gateways? for following scenario:
- Ability to choose different SMS Gateway provider based on Country / ISD Code
- Ability to switch SMS Gateway provider to load balance.
- Ability to choose SMS Gateway provider on the go.

**Comment by shibby** [comment]
they are so hard to implement for a open source addon. they are customer based requests, so i cannot do them.
