### ISSUE TITLE
Message Keeps Saying "Error"

### ISSUE THREAD

**Issue by christogonus** [AktuelSistem/WHMCS-SmsModule#78]
I have tried to install this addon on 2 different WHMCS installations with the latest version of WHMCS installed in each but it does not work.

I have tried to make use of Routesms and Clickatell.  

What could be the curse of all these? Please I need your help.

**Comment by shibby** [comment]
Plesase send a message with debug mode and give us your debug message.
Maybe we can see where is the error?

**Comment by christogonus** [comment]
How can I send message with debug mode. A little instruction could help please.

**Comment by christogonus** [comment]
Debug Result

    Params: {"senderid":"DukeServers","user":"test","pass":"test7","signature":" www.dukeservers.com"}
    To: 2348114246686
    Message: hi chris, how are you? www.dukeservers.com
    SenderClass: routesms
    Request url: http://121.241.242.114:8080/bulksms/bulksms?username=test&password=test7&type=1&dlr=0&destination=2348114246686&source=DukeServers&message=hi+chris%2C+how+are+you%3F++www.dukeservers.com
    Sunucudan dönen cevap: 1703|2348114246686
    Invalid value in username or password field
    Mesaj veritabanına kaydedildi

**Comment by christogonus** [comment]
From the log, I was able to dictate the error and got it fixed. 
Everything works fine. Thanks.
