### ISSUE TITLE
Run Debug mode

### ISSUE THREAD

**Issue by christogonus** [AktuelSistem/WHMCS-SmsModule#79]
How can I send message with debug mode. So that I will know why sms is not sending on 2 different WHMCS installations.

**Comment by christogonus** [comment]
I have this installed on dukeservers.com and ocsp.com.au/hosting but both are not working.
Please help out in this situation please.

**Comment by shibby** [comment]
[Imgur](http://i.imgur.com/XWhAEWd.png)

**Comment by christogonus** [comment]
Debug Result

    Params: {"senderid":"DukeServers","user":"test","pass":"test101","signature":" www.dukeservers.com"}
    To: 2348114246686
    Message: hi chris, how are you? www.dukeservers.com
    SenderClass: routesms
    Request url: http://121.241.242.114:8080/bulksms/bulksms?username=test&password=test101&type=1&dlr=0&destination=2348114246686&source=DukeServers&message=hi+chris%2C+how+are+you%3F++www.dukeservers.com
    Sunucudan dönen cevap: 1703|2348114246686
    Invalid value in username or password field
    Mesaj veritabanına kaydedildi


NOTE:
I have removed my actual username and password because this is an open community. I can inbox you the WHMCS login to the 2 hosting accounts I have this same error on.

**Comment by christogonus** [comment]
Form the log, I was able to dictate the error and got it fixed. 
Everything works fine. Thanks.
