### ISSUE TITLE
not working with whmcs 5.3.8

### ISSUE THREAD

**Issue by vidnar** [AktuelSistem/WHMCS-SmsModule#86]
please update the code for whmcs 5.3.8
many thanks

**Comment by christogonus** [comment]
This addon works perfect on WHMCS5.3, 
I can help you get this fixed.

**Comment by vidnar** [comment]
please help me.

**Comment by christogonus** [comment]
Hi Vidnar,

Let me know the error you are getting.

A screenshot will be nice. Place the screenshot at http://prnt.sc/

**Comment by vidnar** [comment]
http://prntscr.com/9o6mky
marked fields are not working on the screenshot, also msg send not working...

**Comment by christogonus** [comment]
create a temporary admin login, paste the admin here....
I will log on and fix the issue for you.

When I am done in some minutes, you can delete the temporary admin.

Regards.

**Comment by vidnar** [comment]
can u come on teamviewer?

**Comment by christogonus** [comment]
You want me to show you how to do it?
I am trying to download teamviewer right now.

Will let you know once installed

**Comment by vidnar** [comment]
id: 249 875 150
pass: 1965

**Comment by christogonus** [comment]
ready to connect... 
Teamvier in installed right now.

**Comment by vidnar** [comment]
issue resolved. this guy is awesome!!

**Comment by christogonus** [comment]
Thanks man.
More power to your elbow.

**Comment by shibby** [comment]
@christogonus what was the problem and how did you solve it? :)

**Comment by christogonus** [comment]
Hi,
Go to Menu->Setup->Custom Client Fields
Add a field: name=Send Sms, type= Tick box, Show on Order Form=check. (This field will be shown at register page. If user do not check this field, SMS will not send to this user)

Add a field: name=GSM Number, type=Text Box, Show on Order Form=check. (This field will be shown at register page. Sms will send to this value that user fills.)

Let me know if you need further assistance.

**Comment by shibby** [comment]
Hah ok, actually there wasnt any problem/bug. Just nobody cares installation instructions.
